package org.loguno.test.exceptions;

public class CaughtByPythonException extends Exception {
}
